language: cpp

git:
  depth: 1

branches:
  only:
#    - develop
    - /^v\d+\.\d+(\.\d+)?$/

dist: xenial

env:
  global:
    - VERSION="$TRAVIS_TAG"
    - QT_VERSION="5.12.0"

matrix:
  include:
  - os: linux
    env: QTC_VERSION="4.7.0" ARCH="x64"
  - os: linux
    env: QTC_VERSION="4.8.0" ARCH="x64"
  - os: linux
    env: QTC_VERSION="4.9.0" ARCH="x64"
  - os: osx
    env: QTC_VERSION="4.7.0" ARCH="x64"
  - os: osx
    env: QTC_VERSION="4.8.0" ARCH="x64"
  - os: osx
    env: QTC_VERSION="4.9.0" ARCH="x64"
  - os: windows
    env: QTC_VERSION="4.7.0" ARCH="x86"
  - os: windows
    env: QTC_VERSION="4.8.0" ARCH="x86"
  - os: windows
    env: QTC_VERSION="4.9.0" ARCH="x86"
  - os: windows
    env: QTC_VERSION="4.7.0" ARCH="x64"
  - os: windows
    env: QTC_VERSION="4.8.0" ARCH="x64"
  - os: windows
    env: QTC_VERSION="4.9.0" ARCH="x64"

# for some reason qt-creator packages is archives as 7z archives for all operation systems,
# so we need p7zip for macOS and Ubnuntu
addons:
  apt:
    packages:
    - p7zip-full
    - libgl1-mesa-dev
  homebrew:
    packages:
    - p7zip

install:
  - sudo ./util/prepare.sh

script:
  - ./util/build.sh


deploy:
  provider: releases
  api_key:
    secure: fLwNM384pYNkb5Bdd/y412GY2CwkKTfYU0+grEhFkug3lINOQY+z3GpS0QQLMZMQxfOMnSqIEkb2Z2CO70RmZz4UXKhcYZzu5OXmx6NX62OTBEqAjYRFxtYeOhNIwcVjKTyGOclypA13AsJW4MIXIkYge7dBDufD+zks1g1M8tE2XW5caKxSOWpXiV9VyeA3ihXW5FPF0veBbxf7umGIswfX8pV1Os1JJpzZwXW8dAfXnQU88KH7OOfRWf2Ddwd58+Nfwihr4uzre8vdcFEjVUXysR2zC2suv6YCm8kA1NrLi9YujtXO2zRn5EUaqnwY9xS7COYFSWPgb8vtBsrcRPCYXixVu3GHdfVthWQwjozjhOMM454ImJ0m0tvfAhSHZNDAjeDy8yV6NOcARELfmSJC3yJxJ3GZ/WRNmdl4lb4b6vOOJZXzpV5cftvTHK50uxX8Qa5TVv0y6/meoX9JEq2zPcMgVvvRxJj6p/jRWYlo8fX66mCZcKo1Unydh5b1JcDho3sGmdKa7W3FqYFwpc93FbtUDJO/G7jD6f+SaQrA43pxLRpK4tVDZheaeA0YfRUnuR25LataSrMiGY9X4sJnwuO+u2SPHh7DQjKLO8tZhquOcvpApQZfCbPfIGm4FZqBPJlFsSs6uPgyCn8y2Ut3qPha0vQr1oYTJWLTwr4=
  on:
    branch: master
    tags: true
  file_glob: true
  file:
    - "Conan-*.tar.gz"
    - "Conan-*.zip"
  skip_cleanup: true

notifications:
  email: false
