language: cpp

git:
  depth: 1

branches:
  only:
  - develop
  #  - /^v\d+\.\d+(\.\d+)?$/

env:
  - VERSION="$TRAVIS_TAG" QT_VERSION="5.12.0" QTC_VERSION="4.8.0"
  - VERSION="$TRAVIS_TAG" QT_VERSION="5.12.0" QTC_VERSION="4.7.0"

# for some reason qt-creator packages is archives as 7z archives for all operation systems,
# so we need p7zip for macOS and Ubnuntu
addons:
  apt:
    packages:
    - p7zip-full
    - libgl1-mesa-dev
  homebrew:
    packages:
    - p7zip

os:
  - linux
  - osx
  - windows

dist: xenial

install:
  - ./util/prepare.sh

script:
  - ./util/build.sh

deploy:
  provider: releases
  api_key:
    secure: aNWbvyz7vT9LsP2ksG9XheKx/4PKrCH1xRPq9Tsi1z6AZjBa0EhgqhuOvANSel3JDyzcww78ZmmCTnqCKMeJVRqlB0pA3fyqmwcCwQ3QtvuElUiNh/LHBkymXffUfev6TiYHLJPL3juZV81NBaZVA5q4GkjR3BQ5XEH4IfEn2XHxL8czKrs2rr6lYzVvlt7iyEUxX766FLv5WWyzF1Tj1aKun+9whjAwl3CaurWq0ehCN3DnemGgArGRIwPhNXpcAeb8s9HZuO43tHpC0Mn86fJs/U6T7UvyjMU9gE5UvU8iTR99eMyHvP5ySTlxzELVVqJfiFSwcsv3SWwrlPLHasVr7sEayCgHWwvsxVOA1eXXFwFMCo4DHQF/79EPVr8X9a9g9l7qp7NdniFxFbE4k8cS0yUX9+S8TsdLhOm4aE/MJPP5SUY4eYjIZ92Oj8YjSsZ+boIbwCjHPjLIr9uhU8ejBohpXOJ9oR+hiXyuaozn268f7ka1AD6PyMfdqDrxk0EZLyinGxIlzTkkJ0c3cOEqc0DVsftXMV+jLynueve8zvHPKvkOeh9CgJ8d0AdeiS6brKrOKvewmntdM+0ND6dPYshbjtwLJmdlvUcB3dceLNHU7zRUV4r8RRZ52E4kFOLZ9BqzKKfRyDQ/WekKB+EpIaRPvPnC0gRx7g/B2PA=
  on:
    branch: master
    tags: true
  file_glob: true
  file:
    - "Conan-*.tar.gz"
    - "Conan-*.zip"
  skip_cleanup: true
  draft: true

notifications:
  email: false
